version: '3.4'

services:
  0x06unittestsinjs:
    image: 0x06unittestsinjs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
